// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmfyKjxsYSSZTCnKRJQ8Lyl2FUxZ7ImII',
    appId: '1:574670391972:web:22819178cccd3bf8ee3431',
    messagingSenderId: '574670391972',
    projectId: 'fir-flutter-codelab-8daf6',
    authDomain: 'fir-flutter-codelab-8daf6.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-8daf6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBgr9b7AHVAcy6qnjbt8q3q7gd1YBPGRs',
    appId: '1:574670391972:android:ee4af817616dbfbcee3431',
    messagingSenderId: '574670391972',
    projectId: 'fir-flutter-codelab-8daf6',
    storageBucket: 'fir-flutter-codelab-8daf6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjXCkoX7uWqmUTR8uKmr5izoqxbkniN24',
    appId: '1:574670391972:ios:4a68937061627e67ee3431',
    messagingSenderId: '574670391972',
    projectId: 'fir-flutter-codelab-8daf6',
    storageBucket: 'fir-flutter-codelab-8daf6.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjXCkoX7uWqmUTR8uKmr5izoqxbkniN24',
    appId: '1:574670391972:ios:4a68937061627e67ee3431',
    messagingSenderId: '574670391972',
    projectId: 'fir-flutter-codelab-8daf6',
    storageBucket: 'fir-flutter-codelab-8daf6.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
